-- +goose Up
-- +goose StatementBegin
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS estados (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS municipios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    estado_id UUID NOT NULL REFERENCES estados(id),
    UNIQUE(name, estado_id)
);

CREATE TABLE IF NOT EXISTS parroquias (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    municipio_id UUID NOT NULL REFERENCES municipios(id),
    UNIQUE(name, municipio_id)
);

CREATE INDEX IF NOT EXISTS idx_municipios_estado_id ON municipios(estado_id);
CREATE INDEX IF NOT EXISTS idx_parroquias_municipio_id ON parroquias(municipio_id);

INSERT INTO estados (name) VALUES
    ('Amazonas'),
    ('Anzoátegui'),
    ('Apure'),
    ('Aragua'),
    ('Barinas'),
    ('Bolívar'),
    ('Carabobo'),
    ('Cojedes'),
    ('Delta Amacuro'),
    ('Distrito Capital'),
    ('Falcón'),
    ('Guárico'),
    ('Lara'),
    ('La Guaira'),
    ('Mérida'),
    ('Miranda'),
    ('Monagas'),
    ('Nueva Esparta'),
    ('Portuguesa'),
    ('Sucre'),
    ('Táchira'),
    ('Trujillo'),
    ('Yaracuy'),
    ('Zulia');
-- +goose StatementEnd

-- +goose StatementBegin
WITH e AS (SELECT id, name FROM estados)
INSERT INTO municipios (name, estado_id)
SELECT m.name, e.id
FROM (VALUES
  ('Alto Orinoco', 'Amazonas'),
  ('Atabapo', 'Amazonas'),
  ('Atures', 'Amazonas'),
  ('Autana', 'Amazonas'),
  ('Manapiare', 'Amazonas'),
  ('Maroa', 'Amazonas'),
  ('Río Negro', 'Amazonas'),
  ('Anaco', 'Anzoátegui'),
  ('Aragua', 'Anzoátegui'),
  ('Manuel Ezequiel Bruzual', 'Anzoátegui'),
  ('Diego Bautista Urbaneja', 'Anzoátegui'),
  ('Fernando Peñalver', 'Anzoátegui'),
  ('Francisco Del Carmen Carvajal', 'Anzoátegui'),
  ('General Sir Arthur McGregor', 'Anzoátegui'),
  ('Guanta', 'Anzoátegui'),
  ('Independencia', 'Anzoátegui'),
  ('José Gregorio Monagas', 'Anzoátegui'),
  ('Juan Antonio Sotillo', 'Anzoátegui'),
  ('Juan Manuel Cajigal', 'Anzoátegui'),
  ('Libertad', 'Anzoátegui'),
  ('Francisco de Miranda', 'Anzoátegui'),
  ('Pedro María Freites', 'Anzoátegui'),
  ('Píritu', 'Anzoátegui'),
  ('San José de Guanipa', 'Anzoátegui'),
  ('San Juan de Capistrano', 'Anzoátegui'),
  ('Santa Ana', 'Anzoátegui'),
  ('Simón Bolívar', 'Anzoátegui'),
  ('Simón Rodríguez', 'Anzoátegui'),
  ('Achaguas', 'Apure'),
  ('Biruaca', 'Apure'),
  ('Muñóz', 'Apure'),
  ('Páez', 'Apure'),
  ('Pedro Camejo', 'Apure'),
  ('Rómulo Gallegos', 'Apure'),
  ('San Fernando', 'Apure'),
  ('Atanasio Girardot', 'Aragua'),
  ('Bolívar', 'Aragua'),
  ('Camatagua', 'Aragua'),
  ('Francisco Linares Alcántara', 'Aragua'),
  ('José Ángel Lamas', 'Aragua'),
  ('José Félix Ribas', 'Aragua'),
  ('José Rafael Revenga', 'Aragua'),
  ('Libertador', 'Aragua'),
  ('Mario Briceño Iragorry', 'Aragua'),
  ('Ocumare de la Costa de Oro', 'Aragua'),
  ('San Casimiro', 'Aragua'),
  ('San Sebastián', 'Aragua'),
  ('Santiago Mariño', 'Aragua'),
  ('Santos Michelena', 'Aragua'),
  ('Sucre', 'Aragua'),
  ('Tovar', 'Aragua'),
  ('Urdaneta', 'Aragua'),
  ('Zamora', 'Aragua'),
  ('Alberto Arvelo Torrealba', 'Barinas'),
  ('Andrés Eloy Blanco', 'Barinas'),
  ('Antonio José de Sucre', 'Barinas'),
  ('Arismendi', 'Barinas'),
  ('Barinas', 'Barinas'),
  ('Bolívar', 'Barinas'),
  ('Cruz Paredes', 'Barinas'),
  ('Ezequiel Zamora', 'Barinas'),
  ('Obispos', 'Barinas'),
  ('Pedraza', 'Barinas'),
  ('Rojas', 'Barinas'),
  ('Sosa', 'Barinas'),
  ('Caroní', 'Bolívar'),
  ('Cedeño', 'Bolívar'),
  ('El Callao', 'Bolívar'),
  ('Gran Sabana', 'Bolívar'),
  ('Heres', 'Bolívar'),
  ('Piar', 'Bolívar'),
  ('Angostura (Raúl Leoni)', 'Bolívar'),
  ('Roscio', 'Bolívar'),
  ('Sifontes', 'Bolívar'),
  ('Sucre', 'Bolívar'),
  ('Padre Pedro Chien', 'Bolívar'),
  ('Bejuma', 'Carabobo'),
  ('Carlos Arvelo', 'Carabobo'),
  ('Diego Ibarra', 'Carabobo'),
  ('Guacara', 'Carabobo'),
  ('Juan José Mora', 'Carabobo'),
  ('Libertador', 'Carabobo'),
  ('Los Guayos', 'Carabobo'),
  ('Miranda', 'Carabobo'),
  ('Montalbán', 'Carabobo'),
  ('Naguanagua', 'Carabobo'),
  ('Puerto Cabello', 'Carabobo'),
  ('San Diego', 'Carabobo'),
  ('San Joaquín', 'Carabobo'),
  ('Valencia', 'Carabobo'),
  ('Anzoátegui', 'Cojedes'),
  ('Tinaquillo', 'Cojedes'),
  ('Girardot', 'Cojedes'),
  ('Lima Blanco', 'Cojedes'),
  ('Pao de San Juan Bautista', 'Cojedes'),
  ('Ricaurte', 'Cojedes'),
  ('Rómulo Gallegos', 'Cojedes'),
  ('San Carlos', 'Cojedes'),
  ('Tinaco', 'Cojedes'),
  ('Antonio Díaz', 'Delta Amacuro'),
  ('Casacoima', 'Delta Amacuro'),
  ('Pedernales', 'Delta Amacuro'),
  ('Tucupita', 'Delta Amacuro'),
  ('Acosta', 'Falcón'),
  ('Bolívar', 'Falcón'),
  ('Buchivacoa', 'Falcón'),
  ('Cacique Manaure', 'Falcón'),
  ('Carirubana', 'Falcón'),
  ('Colina', 'Falcón'),
  ('Dabajuro', 'Falcón'),
  ('Democracia', 'Falcón'),
  ('Falcón', 'Falcón'),
  ('Federación', 'Falcón'),
  ('Jacura', 'Falcón'),
  ('José Laurencio Silva', 'Falcón'),
  ('Los Taques', 'Falcón'),
  ('Mauroa', 'Falcón'),
  ('Miranda', 'Falcón'),
  ('Monseñor Iturriza', 'Falcón'),
  ('Palmasola', 'Falcón'),
  ('Petit', 'Falcón'),
  ('Píritu', 'Falcón'),
  ('San Francisco', 'Falcón'),
  ('Sucre', 'Falcón'),
  ('Tocópero', 'Falcón'),
  ('Unión', 'Falcón'),
  ('Urumaco', 'Falcón'),
  ('Zamora', 'Falcón'),
  ('Camaguán', 'Guárico'),
  ('Chaguaramas', 'Guárico'),
  ('El Socorro', 'Guárico'),
  ('José Félix Ribas', 'Guárico'),
  ('José Tadeo Monagas', 'Guárico'),
  ('Juan Germán Roscio', 'Guárico'),
  ('Julián Mellado', 'Guárico'),
  ('Las Mercedes', 'Guárico'),
  ('Leonardo Infante', 'Guárico'),
  ('Pedro Zaraza', 'Guárico'),
  ('Ortíz', 'Guárico'),
  ('San Gerónimo de Guayabal', 'Guárico'),
  ('San José de Guaribe', 'Guárico'),
  ('Santa María de Ipire', 'Guárico'),
  ('Sebastián Francisco de Miranda', 'Guárico'),
  ('Andrés Eloy Blanco', 'Lara'),
  ('Crespo', 'Lara'),
  ('Iribarren', 'Lara'),
  ('Jiménez', 'Lara'),
  ('Morán', 'Lara'),
  ('Palavecino', 'Lara'),
  ('Simón Planas', 'Lara'),
  ('Torres', 'Lara'),
  ('Urdaneta', 'Lara'),
  ('Alberto Adriani', 'Mérida'),
  ('Andrés Bello', 'Mérida'),
  ('Antonio Pinto Salinas', 'Mérida'),
  ('Aricagua', 'Mérida'),
  ('Arzobispo Chacón', 'Mérida'),
  ('Campo Elías', 'Mérida'),
  ('Caracciolo Parra Olmedo', 'Mérida'),
  ('Cardenal Quintero', 'Mérida'),
  ('Guaraque', 'Mérida'),
  ('Julio César Salas', 'Mérida'),
  ('Justo Briceño', 'Mérida'),
  ('Libertador', 'Mérida'),
  ('Miranda', 'Mérida'),
  ('Obispo Ramos de Lora', 'Mérida'),
  ('Padre Noguera', 'Mérida'),
  ('Pueblo Llano', 'Mérida'),
  ('Rangel', 'Mérida'),
  ('Rivas Dávila', 'Mérida'),
  ('Santos Marquina', 'Mérida'),
  ('Sucre', 'Mérida'),
  ('Tovar', 'Mérida'),
  ('Tulio Febres Cordero', 'Mérida'),
  ('Zea', 'Mérida'),
  ('Acevedo', 'Miranda'),
  ('Andrés Bello', 'Miranda'),
  ('Baruta', 'Miranda'),
  ('Brión', 'Miranda'),
  ('Buroz', 'Miranda'),
  ('Carrizal', 'Miranda'),
  ('Chacao', 'Miranda'),
  ('Cristóbal Rojas', 'Miranda'),
  ('El Hatillo', 'Miranda'),
  ('Guaicaipuro', 'Miranda'),
  ('Independencia', 'Miranda'),
  ('Lander', 'Miranda'),
  ('Los Salias', 'Miranda'),
  ('Páez', 'Miranda'),
  ('Paz Castillo', 'Miranda'),
  ('Pedro Gual', 'Miranda'),
  ('Plaza', 'Miranda'),
  ('Simón Bolívar', 'Miranda'),
  ('Sucre', 'Miranda'),
  ('Urdaneta', 'Miranda'),
  ('Zamora', 'Miranda'),
  ('Acosta', 'Monagas'),
  ('Aguasay', 'Monagas'),
  ('Bolívar', 'Monagas'),
  ('Caripe', 'Monagas'),
  ('Cedeño', 'Monagas'),
  ('Ezequiel Zamora', 'Monagas'),
  ('Libertador', 'Monagas'),
  ('Maturín', 'Monagas'),
  ('Piar', 'Monagas'),
  ('Punceres', 'Monagas'),
  ('Santa Bárbara', 'Monagas'),
  ('Sotillo', 'Monagas'),
  ('Uracoa', 'Monagas'),
  ('Antolín del Campo', 'Nueva Esparta'),
  ('Arismendi', 'Nueva Esparta'),
  ('García', 'Nueva Esparta'),
  ('Gómez', 'Nueva Esparta'),
  ('Maneiro', 'Nueva Esparta'),
  ('Marcano', 'Nueva Esparta'),
  ('Mariño', 'Nueva Esparta'),
  ('Península de Macanao', 'Nueva Esparta'),
  ('Tubores', 'Nueva Esparta'),
  ('Villalba', 'Nueva Esparta'),
  ('Díaz', 'Nueva Esparta'),
  ('Agua Blanca', 'Portuguesa'),
  ('Araure', 'Portuguesa'),
  ('Esteller', 'Portuguesa'),
  ('Guanare', 'Portuguesa'),
  ('Guanarito', 'Portuguesa'),
  ('Monseñor José Vicente de Unda', 'Portuguesa'),
  ('Ospino', 'Portuguesa'),
  ('Páez', 'Portuguesa'),
  ('Papelón', 'Portuguesa'),
  ('San Genaro de Boconoíto', 'Portuguesa'),
  ('San Rafael de Onoto', 'Portuguesa'),
  ('Santa Rosalía', 'Portuguesa'),
  ('Sucre', 'Portuguesa'),
  ('Turén', 'Portuguesa'),
  ('Andrés Eloy Blanco', 'Sucre'),
  ('Andrés Mata', 'Sucre'),
  ('Arismendi', 'Sucre'),
  ('Benítez', 'Sucre'),
  ('Bermúdez', 'Sucre'),
  ('Bolívar', 'Sucre'),
  ('Cajigal', 'Sucre'),
  ('Cruz Salmerón Acosta', 'Sucre'),
  ('Libertador', 'Sucre'),
  ('Mariño', 'Sucre'),
  ('Mejía', 'Sucre'),
  ('Montes', 'Sucre'),
  ('Ribero', 'Sucre'),
  ('Sucre', 'Sucre'),
  ('Valdéz', 'Sucre'),
  ('Andrés Bello', 'Táchira'),
  ('Antonio Rómulo Costa', 'Táchira'),
  ('Ayacucho', 'Táchira'),
  ('Bolívar', 'Táchira'),
  ('Cárdenas', 'Táchira'),
  ('Córdoba', 'Táchira'),
  ('Fernández Feo', 'Táchira'),
  ('Francisco de Miranda', 'Táchira'),
  ('García de Hevia', 'Táchira'),
  ('Guásimos', 'Táchira'),
  ('Independencia', 'Táchira'),
  ('Jáuregui', 'Táchira'),
  ('José María Vargas', 'Táchira'),
  ('Junín', 'Táchira'),
  ('Libertad', 'Táchira'),
  ('Libertador', 'Táchira'),
  ('Lobatera', 'Táchira'),
  ('Michelena', 'Táchira'),
  ('Panamericano', 'Táchira'),
  ('Pedro María Ureña', 'Táchira'),
  ('Rafael Urdaneta', 'Táchira'),
  ('Samuel Darío Maldonado', 'Táchira'),
  ('San Cristóbal', 'Táchira'),
  ('Seboruco', 'Táchira'),
  ('Simón Rodríguez', 'Táchira'),
  ('Sucre', 'Táchira'),
  ('Torbes', 'Táchira'),
  ('Uribante', 'Táchira'),
  ('San Judas Tadeo', 'Táchira'),
  ('Andrés Bello', 'Trujillo'),
  ('Boconó', 'Trujillo'),
  ('Bolívar', 'Trujillo'),
  ('Candelaria', 'Trujillo'),
  ('Carache', 'Trujillo'),
  ('Escuque', 'Trujillo'),
  ('José Felipe Márquez Cañizalez', 'Trujillo'),
  ('Juan Vicente Campos Elías', 'Trujillo'),
  ('La Ceiba', 'Trujillo'),
  ('Miranda', 'Trujillo'),
  ('Monte Carmelo', 'Trujillo'),
  ('Motatán', 'Trujillo'),
  ('Pampán', 'Trujillo'),
  ('Pampanito', 'Trujillo'),
  ('Rafael Rangel', 'Trujillo'),
  ('San Rafael de Carvajal', 'Trujillo'),
  ('Sucre', 'Trujillo'),
  ('Trujillo', 'Trujillo'),
  ('Urdaneta', 'Trujillo'),
  ('Valera', 'Trujillo'),
  ('Vargas', 'La Guaira'),
  ('Arístides Bastidas', 'Yaracuy'),
  ('Bolívar', 'Yaracuy'),
  ('Bruzual', 'Yaracuy'),
  ('Cocorote', 'Yaracuy'),
  ('Independencia', 'Yaracuy'),
  ('José Antonio Páez', 'Yaracuy'),
  ('La Trinidad', 'Yaracuy'),
  ('Manuel Monge', 'Yaracuy'),
  ('Nirgua', 'Yaracuy'),
  ('Peña', 'Yaracuy'),
  ('San Felipe', 'Yaracuy'),
  ('Sucre', 'Yaracuy'),
  ('Urachiche', 'Yaracuy'),
  ('José Joaquín Veroes', 'Yaracuy'),
  ('Almirante Padilla', 'Zulia'),
  ('Baralt', 'Zulia'),
  ('Cabimas', 'Zulia'),
  ('Catatumbo', 'Zulia'),
  ('Colón', 'Zulia'),
  ('Francisco Javier Pulgar', 'Zulia'),
  ('Páez', 'Zulia'),
  ('Jesús Enrique Losada', 'Zulia'),
  ('Jesús María Semprún', 'Zulia'),
  ('La Cañada de Urdaneta', 'Zulia'),
  ('Lagunillas', 'Zulia'),
  ('Machiques de Perijá', 'Zulia'),
  ('Mara', 'Zulia'),
  ('Maracaibo', 'Zulia'),
  ('Miranda', 'Zulia'),
  ('Rosario de Perijá', 'Zulia'),
  ('San Francisco', 'Zulia'),
  ('Santa Rita', 'Zulia'),
  ('Simón Bolívar', 'Zulia'),
  ('Sucre', 'Zulia'),
  ('Valmore Rodríguez', 'Zulia'),
  ('Libertador', 'Distrito Capital')
) AS m(name, estado_name)
JOIN e ON e.name = m.estado_name;

WITH e AS (SELECT id, name FROM estados),
     m AS (SELECT m.id, m.name, e.name AS estado_name FROM municipios m JOIN estados e ON e.id = m.estado_id)
INSERT INTO parroquias (name, municipio_id)
SELECT p.name, m.id
FROM (VALUES
  ('Alto Orinoco', 'Alto Orinoco', 'Amazonas'),
  ('Huachamacare Acanaña', 'Alto Orinoco', 'Amazonas'),
  ('Marawaka Toky Shamanaña', 'Alto Orinoco', 'Amazonas'),
  ('Mavaka Mavaka', 'Alto Orinoco', 'Amazonas'),
  ('Sierra Parima Parimabé', 'Alto Orinoco', 'Amazonas'),
  ('Ucata Laja Lisa', 'Atabapo', 'Amazonas'),
  ('Yapacana Macuruco', 'Atabapo', 'Amazonas'),
  ('Caname Guarinuma', 'Atabapo', 'Amazonas'),
  ('Fernando Girón Tovar', 'Atures', 'Amazonas'),
  ('Luis Alberto Gómez', 'Atures', 'Amazonas'),
  ('Pahueña Limón de Parhueña', 'Atures', 'Amazonas'),
  ('Platanillal Platanillal', 'Atures', 'Amazonas'),
  ('Samariapo', 'Autana', 'Amazonas'),
  ('Sipapo', 'Autana', 'Amazonas'),
  ('Munduapo', 'Autana', 'Amazonas'),
  ('Guayapo', 'Autana', 'Amazonas'),
  ('Alto Ventuari', 'Manapiare', 'Amazonas'),
  ('Medio Ventuari', 'Manapiare', 'Amazonas'),
  ('Bajo Ventuari', 'Manapiare', 'Amazonas'),
  ('Victorino', 'Maroa', 'Amazonas'),
  ('Comunidad', 'Maroa', 'Amazonas'),
  ('Casiquiare', 'Río Negro', 'Amazonas'),
  ('Cocuy', 'Río Negro', 'Amazonas'),
  ('San Carlos de Río Negro', 'Río Negro', 'Amazonas'),
  ('Solano', 'Río Negro', 'Amazonas'),
  ('Anaco', 'Anaco', 'Anzoátegui'),
  ('San Joaquín', 'Anaco', 'Anzoátegui'),
  ('Cachipo', 'Aragua', 'Anzoátegui'),
  ('Aragua de Barcelona', 'Aragua', 'Anzoátegui'),
  ('Lechería', 'Diego Bautista Urbaneja', 'Anzoátegui'),
  ('El Morro', 'Diego Bautista Urbaneja', 'Anzoátegui'),
  ('Puerto Píritu', 'Fernando Peñalver', 'Anzoátegui'),
  ('San Miguel', 'Fernando Peñalver', 'Anzoátegui'),
  ('Sucre', 'Fernando Peñalver', 'Anzoátegui'),
  ('Valle de Guanape', 'Francisco Del Carmen Carvajal', 'Anzoátegui'),
  ('Santa Bárbara', 'Francisco Del Carmen Carvajal', 'Anzoátegui'),
  ('El Chaparro', 'General Sir Arthur McGregor', 'Anzoátegui'),
  ('Tomás Alfaro', 'General Sir Arthur McGregor', 'Anzoátegui'),
  ('Calatrava', 'General Sir Arthur McGregor', 'Anzoátegui'),
  ('Guanta', 'Guanta', 'Anzoátegui'),
  ('Chorrerón', 'Guanta', 'Anzoátegui'),
  ('Mamo', 'Independencia', 'Anzoátegui'),
  ('Soledad', 'Independencia', 'Anzoátegui'),
  ('Mapire', 'José Gregorio Monagas', 'Anzoátegui'),
  ('Piar', 'José Gregorio Monagas', 'Anzoátegui'),
  ('Santa Clara', 'José Gregorio Monagas', 'Anzoátegui'),
  ('San Diego de Cabrutica', 'José Gregorio Monagas', 'Anzoátegui'),
  ('Uverito', 'José Gregorio Monagas', 'Anzoátegui'),
  ('Zuata', 'José Gregorio Monagas', 'Anzoátegui'),
  ('Puerto La Cruz', 'Juan Antonio Sotillo', 'Anzoátegui'),
  ('Pozuelos', 'Juan Antonio Sotillo', 'Anzoátegui'),
  ('Onoto', 'Juan Manuel Cajigal', 'Anzoátegui'),
  ('San Pablo', 'Juan Manuel Cajigal', 'Anzoátegui'),
  ('San Mateo', 'Libertad', 'Anzoátegui'),
  ('El Carito', 'Libertad', 'Anzoátegui'),
  ('Santa Inés', 'Libertad', 'Anzoátegui'),
  ('La Romereña', 'Libertad', 'Anzoátegui'),
  ('Atapirire', 'Francisco de Miranda', 'Anzoátegui'),
  ('Boca del Pao', 'Francisco de Miranda', 'Anzoátegui'),
  ('El Pao', 'Francisco de Miranda', 'Anzoátegui'),
  ('Pariaguán', 'Francisco de Miranda', 'Anzoátegui'),
  ('Cantaura', 'Pedro María Freites', 'Anzoátegui'),
  ('Libertador', 'Pedro María Freites', 'Anzoátegui'),
  ('Santa Rosa', 'Pedro María Freites', 'Anzoátegui'),
  ('Urica', 'Pedro María Freites', 'Anzoátegui'),
  ('Píritu', 'Píritu', 'Anzoátegui'),
  ('San Francisco', 'Píritu', 'Anzoátegui'),
  ('San José de Guanipa', 'San José de Guanipa', 'Anzoátegui'),
  ('Boca de Uchire', 'San Juan de Capistrano', 'Anzoátegui'),
  ('Boca de Chávez', 'San Juan de Capistrano', 'Anzoátegui'),
  ('Pueblo Nuevo', 'Santa Ana', 'Anzoátegui'),
  ('Santa Ana', 'Santa Ana', 'Anzoátegui'),
  ('Bergantín', 'Simón Bolívar', 'Anzoátegui'),
  ('Caigua', 'Simón Bolívar', 'Anzoátegui'),
  ('El Carmen', 'Simón Bolívar', 'Anzoátegui'),
  ('El Pilar', 'Simón Bolívar', 'Anzoátegui'),
  ('Naricual', 'Simón Bolívar', 'Anzoátegui'),
  ('San Crsitóbal', 'Simón Bolívar', 'Anzoátegui'),
  ('Edmundo Barrios', 'Simón Rodríguez', 'Anzoátegui'),
  ('Miguel Otero Silva', 'Simón Rodríguez', 'Anzoátegui'),
  ('Achaguas', 'Achaguas', 'Apure'),
  ('Apurito', 'Achaguas', 'Apure'),
  ('El Yagual', 'Achaguas', 'Apure'),
  ('Guachara', 'Achaguas', 'Apure'),
  ('Mucuritas', 'Achaguas', 'Apure'),
  ('Queseras del medio', 'Achaguas', 'Apure'),
  ('Biruaca', 'Biruaca', 'Apure'),
  ('Bruzual', 'Muñóz', 'Apure'),
  ('Mantecal', 'Muñóz', 'Apure'),
  ('Quintero', 'Muñóz', 'Apure'),
  ('Rincón Hondo', 'Muñóz', 'Apure'),
  ('San Vicente', 'Muñóz', 'Apure'),
  ('Guasdualito', 'Páez', 'Apure'),
  ('Aramendi', 'Páez', 'Apure'),
  ('El Amparo', 'Páez', 'Apure'),
  ('San Camilo', 'Páez', 'Apure'),
  ('Urdaneta', 'Páez', 'Apure'),
  ('San Juan de Payara', 'Pedro Camejo', 'Apure'),
  ('Codazzi', 'Pedro Camejo', 'Apure'),
  ('Cunaviche', 'Pedro Camejo', 'Apure'),
  ('Elorza', 'Rómulo Gallegos', 'Apure'),
  ('La Trinidad', 'Rómulo Gallegos', 'Apure'),
  ('San Fernando', 'San Fernando', 'Apure'),
  ('El Recreo', 'San Fernando', 'Apure'),
  ('Peñalver', 'San Fernando', 'Apure'),
  ('San Rafael de Atamaica', 'San Fernando', 'Apure'),
  ('Pedro José Ovalles', 'Atanasio Girardot', 'Aragua'),
  ('Joaquín Crespo', 'Atanasio Girardot', 'Aragua'),
  ('José Casanova Godoy', 'Atanasio Girardot', 'Aragua'),
  ('Madre María de San José', 'Atanasio Girardot', 'Aragua'),
  ('Andrés Eloy Blanco', 'Atanasio Girardot', 'Aragua'),
  ('Los Tacarigua', 'Atanasio Girardot', 'Aragua'),
  ('Las Delicias', 'Atanasio Girardot', 'Aragua'),
  ('Choroní', 'Atanasio Girardot', 'Aragua'),
  ('Bolívar', 'Bolívar', 'Aragua'),
  ('Camatagua', 'Camatagua', 'Aragua'),
  ('Carmen de Cura', 'Camatagua', 'Aragua'),
  ('Santa Rita', 'Francisco Linares Alcántara', 'Aragua'),
  ('Francisco de Miranda', 'Francisco Linares Alcántara', 'Aragua'),
  ('Moseñor Feliciano González', 'Francisco Linares Alcántara', 'Aragua'),
  ('Santa Cruz', 'José Ángel Lamas', 'Aragua'),
  ('José Félix Ribas', 'José Félix Ribas', 'Aragua'),
  ('Castor Nieves Ríos', 'José Félix Ribas', 'Aragua'),
  ('Las Guacamayas', 'José Félix Ribas', 'Aragua'),
  ('Pao de Zárate', 'José Félix Ribas', 'Aragua'),
  ('Zuata', 'José Félix Ribas', 'Aragua'),
  ('José Rafael Revenga', 'José Rafael Revenga', 'Aragua'),
  ('Palo Negro', 'Libertador', 'Aragua'),
  ('San Martín de Porres', 'Libertador', 'Aragua'),
  ('El Limón', 'Mario Briceño Iragorry', 'Aragua'),
  ('Caña de Azúcar', 'Mario Briceño Iragorry', 'Aragua'),
  ('Ocumare de la Costa', 'Ocumare de la Costa de Oro', 'Aragua'),
  ('San Casimiro', 'San Casimiro', 'Aragua'),
  ('Güiripa', 'San Casimiro', 'Aragua'),
  ('Ollas de Caramacate', 'San Casimiro', 'Aragua'),
  ('Valle Morín', 'San Casimiro', 'Aragua'),
  ('San Sebastían', 'San Sebastián', 'Aragua'),
  ('Turmero', 'Santiago Mariño', 'Aragua'),
  ('Arevalo Aponte', 'Santiago Mariño', 'Aragua'),
  ('Chuao', 'Santiago Mariño', 'Aragua'),
  ('Samán de Güere', 'Santiago Mariño', 'Aragua'),
  ('Alfredo Pacheco Miranda', 'Santiago Mariño', 'Aragua'),
  ('Santos Michelena', 'Santos Michelena', 'Aragua'),
  ('Tiara', 'Santos Michelena', 'Aragua'),
  ('Cagua', 'Sucre', 'Aragua'),
  ('Bella Vista', 'Sucre', 'Aragua'),
  ('Tovar', 'Tovar', 'Aragua'),
  ('Urdaneta', 'Urdaneta', 'Aragua'),
  ('Las Peñitas', 'Urdaneta', 'Aragua'),
  ('San Francisco de Cara', 'Urdaneta', 'Aragua'),
  ('Taguay', 'Urdaneta', 'Aragua'),
  ('Zamora', 'Zamora', 'Aragua'),
  ('Magdaleno', 'Zamora', 'Aragua'),
  ('San Francisco de Asís', 'Zamora', 'Aragua'),
  ('Valles de Tucutunemo', 'Zamora', 'Aragua'),
  ('Augusto Mijares', 'Zamora', 'Aragua'),
  ('Sabaneta', 'Alberto Arvelo Torrealba', 'Barinas'),
  ('Juan Antonio Rodríguez Domínguez', 'Alberto Arvelo Torrealba', 'Barinas'),
  ('El Cantón', 'Andrés Eloy Blanco', 'Barinas'),
  ('Santa Cruz de Guacas', 'Andrés Eloy Blanco', 'Barinas'),
  ('Puerto Vivas', 'Andrés Eloy Blanco', 'Barinas'),
  ('Ticoporo', 'Antonio José de Sucre', 'Barinas'),
  ('Nicolás Pulido', 'Antonio José de Sucre', 'Barinas'),
  ('Andrés Bello', 'Antonio José de Sucre', 'Barinas'),
  ('Arismendi', 'Arismendi', 'Barinas'),
  ('Guadarrama', 'Arismendi', 'Barinas'),
  ('La Unión', 'Arismendi', 'Barinas'),
  ('San Antonio', 'Arismendi', 'Barinas'),
  ('Barinas', 'Barinas', 'Barinas'),
  ('Alberto Arvelo Larriva', 'Barinas', 'Barinas'),
  ('San Silvestre', 'Barinas', 'Barinas'),
  ('Santa Inés', 'Barinas', 'Barinas'),
  ('Santa Lucía', 'Barinas', 'Barinas'),
  ('Torumos', 'Barinas', 'Barinas'),
  ('El Carmen', 'Barinas', 'Barinas'),
  ('Rómulo Betancourt', 'Barinas', 'Barinas'),
  ('Corazón de Jesús', 'Barinas', 'Barinas'),
  ('Ramón Ignacio Méndez', 'Barinas', 'Barinas'),
  ('Alto Barinas', 'Barinas', 'Barinas'),
  ('Manuel Palacio Fajardo', 'Barinas', 'Barinas'),
  ('Juan Antonio Rodríguez Domínguez', 'Barinas', 'Barinas'),
  ('Dominga Ortiz de Páez', 'Barinas', 'Barinas'),
  ('Barinitas', 'Bolívar', 'Barinas'),
  ('Altamira de Cáceres', 'Bolívar', 'Barinas'),
  ('Calderas', 'Bolívar', 'Barinas'),
  ('Barrancas', 'Cruz Paredes', 'Barinas'),
  ('El Socorro', 'Cruz Paredes', 'Barinas'),
  ('Mazparrito', 'Cruz Paredes', 'Barinas'),
  ('Santa Bárbara', 'Ezequiel Zamora', 'Barinas'),
  ('Pedro Briceño Méndez', 'Ezequiel Zamora', 'Barinas'),
  ('Ramón Ignacio Méndez', 'Ezequiel Zamora', 'Barinas'),
  ('José Ignacio del Pumar', 'Ezequiel Zamora', 'Barinas'),
  ('Obispos', 'Obispos', 'Barinas'),
  ('Guasimitos', 'Obispos', 'Barinas'),
  ('El Real', 'Obispos', 'Barinas'),
  ('La Luz', 'Obispos', 'Barinas'),
  ('Ciudad Bolívia', 'Pedraza', 'Barinas'),
  ('José Ignacio Briceño', 'Pedraza', 'Barinas'),
  ('José Félix Ribas', 'Pedraza', 'Barinas'),
  ('Páez', 'Pedraza', 'Barinas'),
  ('Libertad', 'Rojas', 'Barinas'),
  ('Dolores', 'Rojas', 'Barinas'),
  ('Santa Rosa', 'Rojas', 'Barinas'),
  ('Palacio Fajardo', 'Rojas', 'Barinas'),
  ('Ciudad de Nutrias', 'Sosa', 'Barinas'),
  ('El Regalo', 'Sosa', 'Barinas'),
  ('Puerto Nutrias', 'Sosa', 'Barinas'),
  ('Santa Catalina', 'Sosa', 'Barinas'),
  ('Cachamay', 'Caroní', 'Bolívar'),
  ('Chirica', 'Caroní', 'Bolívar'),
  ('Dalla Costa', 'Caroní', 'Bolívar'),
  ('Once de Abril', 'Caroní', 'Bolívar'),
  ('Simón Bolívar', 'Caroní', 'Bolívar'),
  ('Unare', 'Caroní', 'Bolívar'),
  ('Universidad', 'Caroní', 'Bolívar'),
  ('Vista al Sol', 'Caroní', 'Bolívar'),
  ('Pozo Verde', 'Caroní', 'Bolívar'),
  ('Yocoima', 'Caroní', 'Bolívar'),
  ('5 de Julio', 'Caroní', 'Bolívar'),
  ('Cedeño', 'Cedeño', 'Bolívar'),
  ('Altagracia', 'Cedeño', 'Bolívar'),
  ('Ascensión Farreras', 'Cedeño', 'Bolívar'),
  ('Guaniamo', 'Cedeño', 'Bolívar'),
  ('La Urbana', 'Cedeño', 'Bolívar'),
  ('Pijiguaos', 'Cedeño', 'Bolívar'),
  ('El Callao', 'El Callao', 'Bolívar'),
  ('Gran Sabana', 'Gran Sabana', 'Bolívar'),
  ('Ikabarú', 'Gran Sabana', 'Bolívar'),
  ('Catedral', 'Heres', 'Bolívar'),
  ('Zea', 'Heres', 'Bolívar'),
  ('Orinoco', 'Heres', 'Bolívar'),
  ('José Antonio Páez', 'Heres', 'Bolívar'),
  ('Marhuanta', 'Heres', 'Bolívar'),
  ('Agua Salada', 'Heres', 'Bolívar'),
  ('Vista Hermosa', 'Heres', 'Bolívar'),
  ('La Sabanita', 'Heres', 'Bolívar'),
  ('Panapana', 'Heres', 'Bolívar'),
  ('Andrés Eloy Blanco', 'Piar', 'Bolívar'),
  ('Pedro Cova', 'Piar', 'Bolívar'),
  ('Raúl Leoni', 'Angostura (Raúl Leoni)', 'Bolívar'),
  ('Barceloneta', 'Angostura (Raúl Leoni)', 'Bolívar'),
  ('Santa Bárbara', 'Angostura (Raúl Leoni)', 'Bolívar'),
  ('San Francisco', 'Angostura (Raúl Leoni)', 'Bolívar'),
  ('Roscio', 'Roscio', 'Bolívar'),
  ('Salóm', 'Roscio', 'Bolívar'),
  ('Sifontes', 'Sifontes', 'Bolívar'),
  ('Dalla Costa', 'Sifontes', 'Bolívar'),
  ('San Isidro', 'Sifontes', 'Bolívar'),
  ('Sucre', 'Sucre', 'Bolívar'),
  ('Aripao', 'Sucre', 'Bolívar'),
  ('Guarataro', 'Sucre', 'Bolívar'),
  ('Las Majadas', 'Sucre', 'Bolívar'),
  ('Moitaco', 'Sucre', 'Bolívar'),
  ('Padre Pedro Chien', 'Padre Pedro Chien', 'Bolívar'),
  ('Río Grande', 'Padre Pedro Chien', 'Bolívar'),
  ('Bejuma', 'Bejuma', 'Carabobo'),
  ('Canoabo', 'Bejuma', 'Carabobo'),
  ('Simón Bolívar', 'Bejuma', 'Carabobo'),
  ('Güigüe', 'Carlos Arvelo', 'Carabobo'),
  ('Carabobo', 'Carlos Arvelo', 'Carabobo'),
  ('Tacarigua', 'Carlos Arvelo', 'Carabobo'),
  ('Mariara', 'Diego Ibarra', 'Carabobo'),
  ('Aguas Calientes', 'Diego Ibarra', 'Carabobo'),
  ('Ciudad Alianza', 'Guacara', 'Carabobo'),
  ('Guacara', 'Guacara', 'Carabobo'),
  ('Yagua', 'Guacara', 'Carabobo'),
  ('Morón', 'Juan José Mora', 'Carabobo'),
  ('Yagua', 'Juan José Mora', 'Carabobo'),
  ('Tocuyito', 'Libertador', 'Carabobo'),
  ('Independencia', 'Libertador', 'Carabobo'),
  ('Los Guayos', 'Los Guayos', 'Carabobo'),
  ('Miranda', 'Miranda', 'Carabobo'),
  ('Montalbán', 'Montalbán', 'Carabobo'),
  ('Naguanagua', 'Naguanagua', 'Carabobo'),
  ('Bartolomé Salóm', 'Puerto Cabello', 'Carabobo'),
  ('Democracia', 'Puerto Cabello', 'Carabobo'),
  ('Fraternidad', 'Puerto Cabello', 'Carabobo'),
  ('Goaigoaza', 'Puerto Cabello', 'Carabobo'),
  ('Juan José Flores', 'Puerto Cabello', 'Carabobo'),
  ('Unión', 'Puerto Cabello', 'Carabobo'),
  ('Borburata', 'Puerto Cabello', 'Carabobo'),
  ('Patanemo', 'Puerto Cabello', 'Carabobo'),
  ('San Diego', 'San Diego', 'Carabobo'),
  ('San Joaquín', 'San Joaquín', 'Carabobo'),
  ('Candelaria', 'Valencia', 'Carabobo'),
  ('Catedral', 'Valencia', 'Carabobo'),
  ('El Socorro', 'Valencia', 'Carabobo'),
  ('Miguel Peña', 'Valencia', 'Carabobo'),
  ('Rafael Urdaneta', 'Valencia', 'Carabobo'),
  ('San Blas', 'Valencia', 'Carabobo'),
  ('San José', 'Valencia', 'Carabobo'),
  ('Santa Rosa', 'Valencia', 'Carabobo'),
  ('Negro Primero', 'Valencia', 'Carabobo'),
  ('Cojedes', 'Anzoátegui', 'Cojedes'),
  ('Juan de Mata Suárez', 'Anzoátegui', 'Cojedes'),
  ('Tinaquillo', 'Tinaquillo', 'Cojedes'),
  ('El Baúl', 'Girardot', 'Cojedes'),
  ('Sucre', 'Girardot', 'Cojedes'),
  ('La Aguadita', 'Lima Blanco', 'Cojedes'),
  ('Macapo', 'Lima Blanco', 'Cojedes'),
  ('El Pao', 'Pao de San Juan Bautista', 'Cojedes'),
  ('El Amparo', 'Ricaurte', 'Cojedes'),
  ('Libertad de Cojedes', 'Ricaurte', 'Cojedes'),
  ('Rómulo Gallegos', 'Rómulo Gallegos', 'Cojedes'),
  ('San Carlos de Austria', 'San Carlos', 'Cojedes'),
  ('Juan Ángel Bravo', 'San Carlos', 'Cojedes'),
  ('Manuel Manrique', 'San Carlos', 'Cojedes'),
  ('General en Jefe José Laurencio Silva', 'Tinaco', 'Cojedes'),
  ('Curiapo', 'Antonio Díaz', 'Delta Amacuro'),
  ('Almirante Luis Brión', 'Antonio Díaz', 'Delta Amacuro'),
  ('Francisco Aniceto Lugo', 'Antonio Díaz', 'Delta Amacuro'),
  ('Manuel Renaud', 'Antonio Díaz', 'Delta Amacuro'),
  ('Padre Barral', 'Antonio Díaz', 'Delta Amacuro'),
  ('Santos de Abelgas', 'Antonio Díaz', 'Delta Amacuro'),
  ('Imataca', 'Casacoima', 'Delta Amacuro'),
  ('Cinco de Julio', 'Casacoima', 'Delta Amacuro'),
  ('Juan Bautista Arismendi', 'Casacoima', 'Delta Amacuro'),
  ('Manuel Piar', 'Casacoima', 'Delta Amacuro'),
  ('Rómulo Gallegos', 'Casacoima', 'Delta Amacuro'),
  ('Pedernales', 'Pedernales', 'Delta Amacuro'),
  ('Luis Beltrán Prieto Figueroa', 'Pedernales', 'Delta Amacuro'),
  ('San José (Delta Amacuro)', 'Tucupita', 'Delta Amacuro'),
  ('José Vidal Marcano', 'Tucupita', 'Delta Amacuro'),
  ('Juan Millán', 'Tucupita', 'Delta Amacuro'),
  ('Leonardo Ruíz Pineda', 'Tucupita', 'Delta Amacuro'),
  ('Mariscal Antonio José de Sucre', 'Tucupita', 'Delta Amacuro'),
  ('Monseñor Argimiro García', 'Tucupita', 'Delta Amacuro'),
  ('San Rafael (Delta Amacuro)', 'Tucupita', 'Delta Amacuro'),
  ('Virgen del Valle', 'Tucupita', 'Delta Amacuro'),
  ('Clarines', 'Manuel Ezequiel Bruzual', 'Anzoátegui'),
  ('Guanape', 'Manuel Ezequiel Bruzual', 'Anzoátegui'),
  ('Sabana de Uchire', 'Manuel Ezequiel Bruzual', 'Anzoátegui'),
  ('Capadare', 'Acosta', 'Falcón'),
  ('La Pastora', 'Acosta', 'Falcón'),
  ('Libertador', 'Acosta', 'Falcón'),
  ('San Juan de los Cayos', 'Acosta', 'Falcón'),
  ('Aracua', 'Bolívar', 'Falcón'),
  ('La Peña', 'Bolívar', 'Falcón'),
  ('San Luis', 'Bolívar', 'Falcón'),
  ('Bariro', 'Buchivacoa', 'Falcón'),
  ('Borojó', 'Buchivacoa', 'Falcón'),
  ('Capatárida', 'Buchivacoa', 'Falcón'),
  ('Guajiro', 'Buchivacoa', 'Falcón'),
  ('Seque', 'Buchivacoa', 'Falcón'),
  ('Zazárida', 'Buchivacoa', 'Falcón'),
  ('Valle de Eroa', 'Buchivacoa', 'Falcón'),
  ('Cacique Manaure', 'Cacique Manaure', 'Falcón'),
  ('Norte', 'Carirubana', 'Falcón'),
  ('Carirubana', 'Carirubana', 'Falcón'),
  ('Santa Ana', 'Carirubana', 'Falcón'),
  ('Urbana Punta Cardón', 'Carirubana', 'Falcón'),
  ('La Vela de Coro', 'Colina', 'Falcón'),
  ('Acurigua', 'Colina', 'Falcón'),
  ('Guaibacoa', 'Colina', 'Falcón'),
  ('Las Calderas', 'Colina', 'Falcón'),
  ('Macoruca', 'Colina', 'Falcón'),
  ('Dabajuro', 'Dabajuro', 'Falcón'),
  ('Agua Clara', 'Democracia', 'Falcón'),
  ('Avaria', 'Democracia', 'Falcón'),
  ('Pedregal', 'Democracia', 'Falcón'),
  ('Piedra Grande', 'Democracia', 'Falcón'),
  ('Purureche', 'Democracia', 'Falcón'),
  ('Adaure', 'Falcón', 'Falcón'),
  ('Adícora', 'Falcón', 'Falcón'),
  ('Baraived', 'Falcón', 'Falcón'),
  ('Buena Vista', 'Falcón', 'Falcón'),
  ('Jadacaquiva', 'Falcón', 'Falcón'),
  ('El Vínculo', 'Falcón', 'Falcón'),
  ('El Hato', 'Falcón', 'Falcón'),
  ('Moruy', 'Falcón', 'Falcón'),
  ('Pueblo Nuevo', 'Falcón', 'Falcón'),
  ('Agua Larga', 'Federación', 'Falcón'),
  ('El Paují', 'Federación', 'Falcón'),
  ('Independencia', 'Federación', 'Falcón'),
  ('Mapararí', 'Federación', 'Falcón'),
  ('Agua Linda', 'Jacura', 'Falcón'),
  ('Araurima', 'Jacura', 'Falcón'),
  ('Jacura', 'Jacura', 'Falcón'),
  ('Tucacas', 'José Laurencio Silva', 'Falcón'),
  ('Boca de Aroa', 'José Laurencio Silva', 'Falcón'),
  ('Los Taques', 'Los Taques', 'Falcón'),
  ('Judibana', 'Los Taques', 'Falcón'),
  ('Mene de Mauroa', 'Mauroa', 'Falcón'),
  ('San Félix', 'Mauroa', 'Falcón'),
  ('Casigua', 'Mauroa', 'Falcón'),
  ('Guzmán Guillermo', 'Miranda', 'Falcón'),
  ('Mitare', 'Miranda', 'Falcón'),
  ('Río Seco', 'Miranda', 'Falcón'),
  ('Sabaneta', 'Miranda', 'Falcón'),
  ('San Antonio', 'Miranda', 'Falcón'),
  ('San Gabriel', 'Miranda', 'Falcón'),
  ('Santa Ana', 'Miranda', 'Falcón'),
  ('Boca del Tocuyo', 'Monseñor Iturriza', 'Falcón'),
  ('Chichiriviche', 'Monseñor Iturriza', 'Falcón'),
  ('Tocuyo de la Costa', 'Monseñor Iturriza', 'Falcón'),
  ('Palmasola', 'Palmasola', 'Falcón'),
  ('Cabure', 'Petit', 'Falcón'),
  ('Colina', 'Petit', 'Falcón'),
  ('Curimagua', 'Petit', 'Falcón'),
  ('San José de la Costa', 'Píritu', 'Falcón'),
  ('Píritu', 'Píritu', 'Falcón'),
  ('San Francisco', 'San Francisco', 'Falcón'),
  ('Sucre', 'Sucre', 'Falcón'),
  ('Pecaya', 'Sucre', 'Falcón'),
  ('Tocópero', 'Tocópero', 'Falcón'),
  ('El Charal', 'Unión', 'Falcón'),
  ('Las Vegas del Tuy', 'Unión', 'Falcón'),
  ('Santa Cruz de Bucaral', 'Unión', 'Falcón'),
  ('Bruzual', 'Urumaco', 'Falcón'),
  ('Urumaco', 'Urumaco', 'Falcón'),
  ('Puerto Cumarebo', 'Zamora', 'Falcón'),
  ('La Ciénaga', 'Zamora', 'Falcón'),
  ('La Soledad', 'Zamora', 'Falcón'),
  ('Pueblo Cumarebo', 'Zamora', 'Falcón'),
  ('Zazárida', 'Zamora', 'Falcón'),
  ('Churuguara', 'Federación', 'Falcón'),
  ('Camaguán', 'Camaguán', 'Guárico'),
  ('Puerto Miranda', 'Camaguán', 'Guárico'),
  ('Uverito', 'Camaguán', 'Guárico'),
  ('Chaguaramas', 'Chaguaramas', 'Guárico'),
  ('El Socorro', 'El Socorro', 'Guárico'),
  ('Tucupido', 'José Félix Ribas', 'Guárico'),
  ('San Rafael de Laya', 'José Félix Ribas', 'Guárico'),
  ('Altagracia de Orituco', 'José Tadeo Monagas', 'Guárico'),
  ('San Rafael de Orituco', 'José Tadeo Monagas', 'Guárico'),
  ('San Francisco Javier de Lezama', 'José Tadeo Monagas', 'Guárico'),
  ('Paso Real de Macaira', 'José Tadeo Monagas', 'Guárico'),
  ('Carlos Soublette', 'José Tadeo Monagas', 'Guárico'),
  ('San Francisco de Macaira', 'José Tadeo Monagas', 'Guárico'),
  ('Libertad de Orituco', 'José Tadeo Monagas', 'Guárico'),
  ('Cantaclaro', 'Juan Germán Roscio', 'Guárico'),
  ('San Juan de los Morros', 'Juan Germán Roscio', 'Guárico'),
  ('Parapara', 'Juan Germán Roscio', 'Guárico'),
  ('El Sombrero', 'Julián Mellado', 'Guárico'),
  ('Sosa', 'Julián Mellado', 'Guárico'),
  ('Las Mercedes', 'Las Mercedes', 'Guárico'),
  ('Cabruta', 'Las Mercedes', 'Guárico'),
  ('Santa Rita de Manapire', 'Las Mercedes', 'Guárico'),
  ('Valle de la Pascua', 'Leonardo Infante', 'Guárico'),
  ('Espino', 'Leonardo Infante', 'Guárico'),
  ('San José de Unare', 'Pedro Zaraza', 'Guárico'),
  ('Zaraza', 'Pedro Zaraza', 'Guárico'),
  ('San José de Tiznados', 'Ortíz', 'Guárico'),
  ('San Francisco de Tiznados', 'Ortíz', 'Guárico'),
  ('San Lorenzo de Tiznados', 'Ortíz', 'Guárico'),
  ('Ortiz', 'Ortíz', 'Guárico'),
  ('Guayabal', 'San Gerónimo de Guayabal', 'Guárico'),
  ('Cazorla', 'San Gerónimo de Guayabal', 'Guárico'),
  ('San José de Guaribe', 'San José de Guaribe', 'Guárico'),
  ('Uveral', 'San José de Guaribe', 'Guárico'),
  ('Santa María de Ipire', 'Santa María de Ipire', 'Guárico'),
  ('Altamira', 'Santa María de Ipire', 'Guárico'),
  ('El Calvario', 'Sebastián Francisco de Miranda', 'Guárico'),
  ('El Rastro', 'Sebastián Francisco de Miranda', 'Guárico'),
  ('Guardatinajas', 'Sebastián Francisco de Miranda', 'Guárico'),
  ('Capital Urbana Calabozo', 'Sebastián Francisco de Miranda', 'Guárico'),
  ('Quebrada Honda de Guache', 'Andrés Eloy Blanco', 'Lara'),
  ('Pío Tamayo', 'Andrés Eloy Blanco', 'Lara'),
  ('Yacambú', 'Andrés Eloy Blanco', 'Lara'),
  ('Fréitez', 'Crespo', 'Lara'),
  ('José María Blanco', 'Crespo', 'Lara'),
  ('Catedral', 'Iribarren', 'Lara'),
  ('Concepción', 'Iribarren', 'Lara'),
  ('El Cují', 'Iribarren', 'Lara'),
  ('Juan de Villegas', 'Iribarren', 'Lara'),
  ('Santa Rosa', 'Iribarren', 'Lara'),
  ('Tamaca', 'Iribarren', 'Lara'),
  ('Unión', 'Iribarren', 'Lara'),
  ('Aguedo Felipe Alvarado', 'Iribarren', 'Lara'),
  ('Buena Vista', 'Iribarren', 'Lara'),
  ('Juárez', 'Iribarren', 'Lara'),
  ('Juan Bautista Rodríguez', 'Jiménez', 'Lara'),
  ('Cuara', 'Jiménez', 'Lara'),
  ('Diego de Lozada', 'Jiménez', 'Lara'),
  ('Paraíso de San José', 'Jiménez', 'Lara'),
  ('San Miguel', 'Jiménez', 'Lara'),
  ('Tintorero', 'Jiménez', 'Lara'),
  ('José Bernardo Dorante', 'Jiménez', 'Lara'),
  ('Coronel Mariano Peraza ', 'Jiménez', 'Lara'),
  ('Bolívar', 'Morán', 'Lara'),
  ('Anzoátegui', 'Morán', 'Lara'),
  ('Guarico', 'Morán', 'Lara'),
  ('Hilario Luna y Luna', 'Morán', 'Lara'),
  ('Humocaro Alto', 'Morán', 'Lara'),
  ('Humocaro Bajo', 'Morán', 'Lara'),
  ('La Candelaria', 'Morán', 'Lara'),
  ('Morán', 'Morán', 'Lara'),
  ('Cabudare', 'Palavecino', 'Lara'),
  ('José Gregorio Bastidas', 'Palavecino', 'Lara'),
  ('Agua Viva', 'Palavecino', 'Lara'),
  ('Sarare', 'Simón Planas', 'Lara'),
  ('Buría', 'Simón Planas', 'Lara'),
  ('Gustavo Vegas León', 'Simón Planas', 'Lara'),
  ('Trinidad Samuel', 'Torres', 'Lara'),
  ('Antonio Díaz', 'Torres', 'Lara'),
  ('Camacaro', 'Torres', 'Lara'),
  ('Castañeda', 'Torres', 'Lara'),
  ('Cecilio Zubillaga', 'Torres', 'Lara'),
  ('Chiquinquirá', 'Torres', 'Lara'),
  ('El Blanco', 'Torres', 'Lara'),
  ('Espinoza de los Monteros', 'Torres', 'Lara'),
  ('Lara', 'Torres', 'Lara'),
  ('Las Mercedes', 'Torres', 'Lara'),
  ('Manuel Morillo', 'Torres', 'Lara'),
  ('Montaña Verde', 'Torres', 'Lara'),
  ('Montes de Oca', 'Torres', 'Lara'),
  ('Torres', 'Torres', 'Lara'),
  ('Heriberto Arroyo', 'Torres', 'Lara'),
  ('Reyes Vargas', 'Torres', 'Lara'),
  ('Altagracia', 'Torres', 'Lara'),
  ('Siquisique', 'Urdaneta', 'Lara'),
  ('Moroturo', 'Urdaneta', 'Lara'),
  ('San Miguel', 'Urdaneta', 'Lara'),
  ('Xaguas', 'Urdaneta', 'Lara'),
  ('Presidente Betancourt', 'Alberto Adriani', 'Mérida'),
  ('Presidente Páez', 'Alberto Adriani', 'Mérida'),
  ('Presidente Rómulo Gallegos', 'Alberto Adriani', 'Mérida'),
  ('Gabriel Picón González', 'Alberto Adriani', 'Mérida'),
  ('Héctor Amable Mora', 'Alberto Adriani', 'Mérida'),
  ('José Nucete Sardi', 'Alberto Adriani', 'Mérida'),
  ('Pulido Méndez', 'Alberto Adriani', 'Mérida'),
  ('La Azulita', 'Andrés Bello', 'Mérida'),
  ('Santa Cruz de Mora', 'Antonio Pinto Salinas', 'Mérida'),
  ('Mesa Bolívar', 'Antonio Pinto Salinas', 'Mérida'),
  ('Mesa de Las Palmas', 'Antonio Pinto Salinas', 'Mérida'),
  ('Aricagua', 'Aricagua', 'Mérida'),
  ('San Antonio', 'Aricagua', 'Mérida'),
  ('Canagua', 'Arzobispo Chacón', 'Mérida'),
  ('Capurí', 'Arzobispo Chacón', 'Mérida'),
  ('Chacantá', 'Arzobispo Chacón', 'Mérida'),
  ('El Molino', 'Arzobispo Chacón', 'Mérida'),
  ('Guaimaral', 'Arzobispo Chacón', 'Mérida'),
  ('Mucutuy', 'Arzobispo Chacón', 'Mérida'),
  ('Mucuchachí', 'Arzobispo Chacón', 'Mérida'),
  ('Fernández Peña', 'Campo Elías', 'Mérida'),
  ('Matriz', 'Campo Elías', 'Mérida'),
  ('Montalbán', 'Campo Elías', 'Mérida'),
  ('Acequias', 'Campo Elías', 'Mérida'),
  ('Jají', 'Campo Elías', 'Mérida'),
  ('La Mesa', 'Campo Elías', 'Mérida'),
  ('San José del Sur', 'Campo Elías', 'Mérida'),
  ('Tucaní', 'Caracciolo Parra Olmedo', 'Mérida'),
  ('Florencio Ramírez', 'Caracciolo Parra Olmedo', 'Mérida'),
  ('Santo Domingo', 'Cardenal Quintero', 'Mérida'),
  ('Las Piedras', 'Cardenal Quintero', 'Mérida'),
  ('Guaraque', 'Guaraque', 'Mérida'),
  ('Mesa de Quintero', 'Guaraque', 'Mérida'),
  ('Río Negro', 'Guaraque', 'Mérida'),
  ('Arapuey', 'Julio César Salas', 'Mérida'),
  ('Palmira', 'Julio César Salas', 'Mérida'),
  ('San Cristóbal de Torondoy', 'Justo Briceño', 'Mérida'),
  ('Torondoy', 'Justo Briceño', 'Mérida'),
  ('Antonio Spinetti Dini', 'Libertador', 'Mérida'),
  ('Arias', 'Libertador', 'Mérida'),
  ('Caracciolo Parra Pérez', 'Libertador', 'Mérida'),
  ('Domingo Peña', 'Libertador', 'Mérida'),
  ('El Llano', 'Libertador', 'Mérida'),
  ('Gonzalo Picón Febres', 'Libertador', 'Mérida'),
  ('Jacinto Plaza', 'Libertador', 'Mérida'),
  ('Juan Rodríguez Suárez', 'Libertador', 'Mérida'),
  ('Lasso de la Vega', 'Libertador', 'Mérida'),
  ('Mariano Picón Salas', 'Libertador', 'Mérida'),
  ('Milla', 'Libertador', 'Mérida'),
  ('Osuna Rodríguez', 'Libertador', 'Mérida'),
  ('Sagrario', 'Libertador', 'Mérida'),
  ('El Morro', 'Libertador', 'Mérida'),
  ('Los Nevados', 'Libertador', 'Mérida'),
  ('Andrés Eloy Blanco', 'Miranda', 'Mérida'),
  ('La Venta', 'Miranda', 'Mérida'),
  ('Piñango', 'Miranda', 'Mérida'),
  ('Timotes', 'Miranda', 'Mérida'),
  ('Eloy Paredes', 'Obispo Ramos de Lora', 'Mérida'),
  ('San Rafael de Alcázar', 'Obispo Ramos de Lora', 'Mérida'),
  ('Santa Elena de Arenales', 'Obispo Ramos de Lora', 'Mérida'),
  ('Santa María de Caparo', 'Padre Noguera', 'Mérida'),
  ('Pueblo Llano', 'Pueblo Llano', 'Mérida'),
  ('Cacute', 'Rangel', 'Mérida'),
  ('La Toma', 'Rangel', 'Mérida'),
  ('Mucuchíes', 'Rangel', 'Mérida'),
  ('Mucurubá', 'Rangel', 'Mérida'),
  ('San Rafael', 'Rangel', 'Mérida'),
  ('Gerónimo Maldonado', 'Rivas Dávila', 'Mérida'),
  ('Bailadores', 'Rivas Dávila', 'Mérida'),
  ('Tabay', 'Santos Marquina', 'Mérida'),
  ('Chiguará', 'Sucre', 'Mérida'),
  ('Estánquez', 'Sucre', 'Mérida'),
  ('Lagunillas', 'Sucre', 'Mérida'),
  ('La Trampa', 'Sucre', 'Mérida'),
  ('Pueblo Nuevo del Sur', 'Sucre', 'Mérida'),
  ('San Juan', 'Sucre', 'Mérida'),
  ('El Amparo', 'Tovar', 'Mérida'),
  ('El Llano', 'Tovar', 'Mérida'),
  ('San Francisco', 'Tovar', 'Mérida'),
  ('Tovar', 'Tovar', 'Mérida'),
  ('Independencia', 'Tulio Febres Cordero', 'Mérida'),
  ('María de la Concepción Palacios Blanco', 'Tulio Febres Cordero', 'Mérida'),
  ('Nueva Bolivia', 'Tulio Febres Cordero', 'Mérida'),
  ('Santa Apolonia', 'Tulio Febres Cordero', 'Mérida'),
  ('Caño El Tigre', 'Zea', 'Mérida'),
  ('Zea', 'Zea', 'Mérida'),
  ('Aragüita', 'Acevedo', 'Miranda'),
  ('Arévalo González', 'Acevedo', 'Miranda'),
  ('Capaya', 'Acevedo', 'Miranda'),
  ('Caucagua', 'Acevedo', 'Miranda'),
  ('Panaquire', 'Acevedo', 'Miranda'),
  ('Ribas', 'Acevedo', 'Miranda'),
  ('El Café', 'Acevedo', 'Miranda'),
  ('Marizapa', 'Acevedo', 'Miranda'),
  ('Cumbo', 'Andrés Bello', 'Miranda'),
  ('San José de Barlovento', 'Andrés Bello', 'Miranda'),
  ('El Cafetal', 'Baruta', 'Miranda'),
  ('Las Minas', 'Baruta', 'Miranda'),
  ('Nuestra Señora del Rosario', 'Baruta', 'Miranda'),
  ('Higuerote', 'Brión', 'Miranda'),
  ('Curiepe', 'Brión', 'Miranda'),
  ('Tacarigua de Brión', 'Brión', 'Miranda'),
  ('Mamporal', 'Buroz', 'Miranda'),
  ('Carrizal', 'Carrizal', 'Miranda'),
  ('Chacao', 'Chacao', 'Miranda'),
  ('Charallave', 'Cristóbal Rojas', 'Miranda'),
  ('Las Brisas', 'Cristóbal Rojas', 'Miranda'),
  ('El Hatillo', 'El Hatillo', 'Miranda'),
  ('Altagracia de la Montaña', 'Guaicaipuro', 'Miranda'),
  ('Cecilio Acosta', 'Guaicaipuro', 'Miranda'),
  ('Los Teques', 'Guaicaipuro', 'Miranda'),
  ('El Jarillo', 'Guaicaipuro', 'Miranda'),
  ('San Pedro', 'Guaicaipuro', 'Miranda'),
  ('Tácata', 'Guaicaipuro', 'Miranda'),
  ('Paracotos', 'Guaicaipuro', 'Miranda'),
  ('Cartanal', 'Independencia', 'Miranda'),
  ('Santa Teresa del Tuy', 'Independencia', 'Miranda'),
  ('La Democracia', 'Lander', 'Miranda'),
  ('Ocumare del Tuy', 'Lander', 'Miranda'),
  ('Santa Bárbara', 'Lander', 'Miranda'),
  ('San Antonio de los Altos', 'Los Salias', 'Miranda'),
  ('Río Chico', 'Páez', 'Miranda'),
  ('El Guapo', 'Páez', 'Miranda'),
  ('Tacarigua de la Laguna', 'Páez', 'Miranda'),
  ('Paparo', 'Páez', 'Miranda'),
  ('San Fernando del Guapo', 'Páez', 'Miranda'),
  ('Santa Lucía del Tuy', 'Paz Castillo', 'Miranda'),
  ('Cúpira', 'Pedro Gual', 'Miranda'),
  ('Machurucuto', 'Pedro Gual', 'Miranda'),
  ('Guarenas', 'Plaza', 'Miranda'),
  ('San Antonio de Yare', 'Simón Bolívar', 'Miranda'),
  ('San Francisco de Yare', 'Simón Bolívar', 'Miranda'),
  ('Leoncio Martínez', 'Sucre', 'Miranda'),
  ('Petare', 'Sucre', 'Miranda'),
  ('Caucagüita', 'Sucre', 'Miranda'),
  ('Filas de Mariche', 'Sucre', 'Miranda'),
  ('La Dolorita', 'Sucre', 'Miranda'),
  ('Cúa', 'Urdaneta', 'Miranda'),
  ('Nueva Cúa', 'Urdaneta', 'Miranda'),
  ('Guatire', 'Zamora', 'Miranda'),
  ('Bolívar', 'Zamora', 'Miranda'),
  ('San Antonio de Maturín', 'Acosta', 'Monagas'),
  ('San Francisco de Maturín', 'Acosta', 'Monagas'),
  ('Aguasay', 'Aguasay', 'Monagas'),
  ('Caripito', 'Bolívar', 'Monagas'),
  ('El Guácharo', 'Caripe', 'Monagas'),
  ('La Guanota', 'Caripe', 'Monagas'),
  ('Sabana de Piedra', 'Caripe', 'Monagas'),
  ('San Agustín', 'Caripe', 'Monagas'),
  ('Teresen', 'Caripe', 'Monagas'),
  ('Caripe', 'Caripe', 'Monagas'),
  ('Areo', 'Cedeño', 'Monagas'),
  ('Capital Cedeño', 'Cedeño', 'Monagas'),
  ('San Félix de Cantalicio', 'Cedeño', 'Monagas'),
  ('Viento Fresco', 'Cedeño', 'Monagas'),
  ('El Tejero', 'Ezequiel Zamora', 'Monagas'),
  ('Punta de Mata', 'Ezequiel Zamora', 'Monagas'),
  ('Chaguaramas', 'Libertador', 'Monagas'),
  ('Las Alhuacas', 'Libertador', 'Monagas'),
  ('Tabasca', 'Libertador', 'Monagas'),
  ('Temblador', 'Libertador', 'Monagas'),
  ('Alto de los Godos', 'Maturín', 'Monagas'),
  ('Boquerón', 'Maturín', 'Monagas'),
  ('Las Cocuizas', 'Maturín', 'Monagas'),
  ('La Cruz', 'Maturín', 'Monagas'),
  ('San Simón', 'Maturín', 'Monagas'),
  ('El Corozo', 'Maturín', 'Monagas'),
  ('El Furrial', 'Maturín', 'Monagas'),
  ('Jusepín', 'Maturín', 'Monagas'),
  ('La Pica', 'Maturín', 'Monagas'),
  ('San Vicente', 'Maturín', 'Monagas'),
  ('Aparicio', 'Piar', 'Monagas'),
  ('Aragua de Maturín', 'Piar', 'Monagas'),
  ('Chaguamal', 'Piar', 'Monagas'),
  ('El Pinto', 'Piar', 'Monagas'),
  ('Guanaguana', 'Piar', 'Monagas'),
  ('La Toscana', 'Piar', 'Monagas'),
  ('Taguaya', 'Piar', 'Monagas'),
  ('Cachipo', 'Punceres', 'Monagas'),
  ('Quiriquire', 'Punceres', 'Monagas'),
  ('Santa Bárbara', 'Santa Bárbara', 'Monagas'),
  ('Barrancas', 'Sotillo', 'Monagas'),
  ('Los Barrancos de Fajardo', 'Sotillo', 'Monagas'),
  ('Uracoa', 'Uracoa', 'Monagas'),
  ('Antolín del Campo', 'Antolín del Campo', 'Nueva Esparta'),
  ('Arismendi', 'Arismendi', 'Nueva Esparta'),
  ('García', 'García', 'Nueva Esparta'),
  ('Francisco Fajardo', 'García', 'Nueva Esparta'),
  ('Bolívar', 'Gómez', 'Nueva Esparta'),
  ('Guevara', 'Gómez', 'Nueva Esparta'),
  ('Matasiete', 'Gómez', 'Nueva Esparta'),
  ('Santa Ana', 'Gómez', 'Nueva Esparta'),
  ('Sucre', 'Gómez', 'Nueva Esparta'),
  ('Aguirre', 'Maneiro', 'Nueva Esparta'),
  ('Maneiro', 'Maneiro', 'Nueva Esparta'),
  ('Adrián', 'Marcano', 'Nueva Esparta'),
  ('Juan Griego', 'Marcano', 'Nueva Esparta'),
  ('Yaguaraparo', 'Marcano', 'Nueva Esparta'),
  ('Porlamar', 'Mariño', 'Nueva Esparta'),
  ('San Francisco de Macanao', 'Península de Macanao', 'Nueva Esparta'),
  ('Boca de Río', 'Península de Macanao', 'Nueva Esparta'),
  ('Tubores', 'Tubores', 'Nueva Esparta'),
  ('Los Baleales', 'Tubores', 'Nueva Esparta'),
  ('Vicente Fuentes', 'Villalba', 'Nueva Esparta'),
  ('Villalba', 'Villalba', 'Nueva Esparta'),
  ('San Juan Bautista', 'Díaz', 'Nueva Esparta'),
  ('Zabala', 'Díaz', 'Nueva Esparta'),
  ('Capital Araure', 'Araure', 'Portuguesa'),
  ('Río Acarigua', 'Araure', 'Portuguesa'),
  ('Capital Esteller', 'Esteller', 'Portuguesa'),
  ('Uveral', 'Esteller', 'Portuguesa'),
  ('Guanare', 'Guanare', 'Portuguesa'),
  ('Córdoba', 'Guanare', 'Portuguesa'),
  ('San José de la Montaña', 'Guanare', 'Portuguesa'),
  ('San Juan de Guanaguanare', 'Guanare', 'Portuguesa'),
  ('Virgen de la Coromoto', 'Guanare', 'Portuguesa'),
  ('Guanarito', 'Guanarito', 'Portuguesa'),
  ('Trinidad de la Capilla', 'Guanarito', 'Portuguesa'),
  ('Divina Pastora', 'Guanarito', 'Portuguesa'),
  ('Monseñor José Vicente de Unda', 'Monseñor José Vicente de Unda', 'Portuguesa'),
  ('Peña Blanca', 'Monseñor José Vicente de Unda', 'Portuguesa'),
  ('Capital Ospino', 'Ospino', 'Portuguesa'),
  ('Aparición', 'Ospino', 'Portuguesa'),
  ('La Estación', 'Ospino', 'Portuguesa'),
  ('Páez', 'Páez', 'Portuguesa'),
  ('Payara', 'Páez', 'Portuguesa'),
  ('Pimpinela', 'Páez', 'Portuguesa'),
  ('Ramón Peraza', 'Páez', 'Portuguesa'),
  ('Papelón', 'Papelón', 'Portuguesa'),
  ('Caño Delgadito', 'Papelón', 'Portuguesa'),
  ('San Genaro de Boconoito', 'San Genaro de Boconoíto', 'Portuguesa'),
  ('Antolín Tovar', 'San Genaro de Boconoíto', 'Portuguesa'),
  ('San Rafael de Onoto', 'San Rafael de Onoto', 'Portuguesa'),
  ('Santa Fe', 'San Rafael de Onoto', 'Portuguesa'),
  ('Thermo Morles', 'San Rafael de Onoto', 'Portuguesa'),
  ('Santa Rosalía', 'Santa Rosalía', 'Portuguesa'),
  ('Florida', 'Santa Rosalía', 'Portuguesa'),
  ('Sucre', 'Sucre', 'Portuguesa'),
  ('Concepción', 'Sucre', 'Portuguesa'),
  ('San Rafael de Palo Alzado', 'Sucre', 'Portuguesa'),
  ('Uvencio Antonio Velásquez', 'Sucre', 'Portuguesa'),
  ('San José de Saguaz', 'Sucre', 'Portuguesa'),
  ('Villa Rosa', 'Sucre', 'Portuguesa'),
  ('Turén', 'Turén', 'Portuguesa'),
  ('Canelones', 'Turén', 'Portuguesa'),
  ('Santa Cruz', 'Turén', 'Portuguesa'),
  ('San Isidro Labrador', 'Turén', 'Portuguesa'),
  ('Mariño', 'Andrés Eloy Blanco', 'Sucre'),
  ('Rómulo Gallegos', 'Andrés Eloy Blanco', 'Sucre'),
  ('San José de Aerocuar', 'Andrés Mata', 'Sucre'),
  ('Tavera Acosta', 'Andrés Mata', 'Sucre'),
  ('Río Caribe', 'Arismendi', 'Sucre'),
  ('Antonio José de Sucre', 'Arismendi', 'Sucre'),
  ('El Morro de Puerto Santo', 'Arismendi', 'Sucre'),
  ('Puerto Santo', 'Arismendi', 'Sucre'),
  ('San Juan de las Galdonas', 'Arismendi', 'Sucre'),
  ('El Pilar', 'Benítez', 'Sucre'),
  ('El Rincón', 'Benítez', 'Sucre'),
  ('General Francisco Antonio Váquez', 'Benítez', 'Sucre'),
  ('Guaraúnos', 'Benítez', 'Sucre'),
  ('Tunapuicito', 'Benítez', 'Sucre'),
  ('Unión', 'Benítez', 'Sucre'),
  ('Santa Catalina', 'Bermúdez', 'Sucre'),
  ('Santa Rosa', 'Bermúdez', 'Sucre'),
  ('Santa Teresa', 'Bermúdez', 'Sucre'),
  ('Bolívar', 'Bermúdez', 'Sucre'),
  ('Maracapana', 'Bermúdez', 'Sucre'),
  ('Libertad', 'Cajigal', 'Sucre'),
  ('El Paujil', 'Cajigal', 'Sucre'),
  ('Yaguaraparo', 'Cajigal', 'Sucre'),
  ('Cruz Salmerón Acosta', 'Cruz Salmerón Acosta', 'Sucre'),
  ('Chacopata', 'Cruz Salmerón Acosta', 'Sucre'),
  ('Manicuare', 'Cruz Salmerón Acosta', 'Sucre'),
  ('Tunapuy', 'Libertador', 'Sucre'),
  ('Campo Elías', 'Libertador', 'Sucre'),
  ('Irapa', 'Mariño', 'Sucre'),
  ('Campo Claro', 'Mariño', 'Sucre'),
  ('Maraval', 'Mariño', 'Sucre'),
  ('San Antonio de Irapa', 'Mariño', 'Sucre'),
  ('Soro', 'Mariño', 'Sucre'),
  ('Mejía', 'Mejía', 'Sucre'),
  ('Cumanacoa', 'Montes', 'Sucre'),
  ('Arenas', 'Montes', 'Sucre'),
  ('Aricagua', 'Montes', 'Sucre'),
  ('Cogollar', 'Montes', 'Sucre'),
  ('San Fernando', 'Montes', 'Sucre'),
  ('San Lorenzo', 'Montes', 'Sucre'),
  ('Villa Frontado (Muelle de Cariaco)', 'Ribero', 'Sucre'),
  ('Catuaro', 'Ribero', 'Sucre'),
  ('Rendón', 'Ribero', 'Sucre'),
  ('San Cruz', 'Ribero', 'Sucre'),
  ('Santa María', 'Ribero', 'Sucre'),
  ('Altagracia', 'Sucre', 'Sucre'),
  ('Santa Inés', 'Sucre', 'Sucre'),
  ('Valentín Valiente', 'Sucre', 'Sucre'),
  ('Ayacucho', 'Sucre', 'Sucre'),
  ('San Juan', 'Sucre', 'Sucre'),
  ('Raúl Leoni', 'Sucre', 'Sucre'),
  ('Gran Mariscal', 'Sucre', 'Sucre'),
  ('Cristóbal Colón', 'Valdéz', 'Sucre'),
  ('Bideau', 'Valdéz', 'Sucre'),
  ('Punta de Piedras', 'Valdéz', 'Sucre'),
  ('Güiria', 'Valdéz', 'Sucre'),
  ('Andrés Bello', 'Andrés Bello', 'Táchira'),
  ('Antonio Rómulo Costa', 'Antonio Rómulo Costa', 'Táchira'),
  ('Ayacucho', 'Ayacucho', 'Táchira'),
  ('Rivas Berti', 'Ayacucho', 'Táchira'),
  ('San Pedro del Río', 'Ayacucho', 'Táchira'),
  ('Bolívar', 'Bolívar', 'Táchira'),
  ('Palotal', 'Bolívar', 'Táchira'),
  ('General Juan Vicente Gómez', 'Bolívar', 'Táchira'),
  ('Isaías Medina Angarita', 'Bolívar', 'Táchira'),
  ('Cárdenas', 'Cárdenas', 'Táchira'),
  ('Amenodoro Ángel Lamus', 'Cárdenas', 'Táchira'),
  ('La Florida', 'Cárdenas', 'Táchira'),
  ('Córdoba', 'Córdoba', 'Táchira'),
  ('Fernández Feo', 'Fernández Feo', 'Táchira'),
  ('Alberto Adriani', 'Fernández Feo', 'Táchira'),
  ('Santo Domingo', 'Fernández Feo', 'Táchira'),
  ('Francisco de Miranda', 'Francisco de Miranda', 'Táchira'),
  ('García de Hevia', 'García de Hevia', 'Táchira'),
  ('Boca de Grita', 'García de Hevia', 'Táchira'),
  ('José Antonio Páez', 'García de Hevia', 'Táchira'),
  ('Guásimos', 'Guásimos', 'Táchira'),
  ('Independencia', 'Independencia', 'Táchira'),
  ('Juan Germán Roscio', 'Independencia', 'Táchira'),
  ('Román Cárdenas', 'Independencia', 'Táchira'),
  ('Jáuregui', 'Jáuregui', 'Táchira'),
  ('Emilio Constantino Guerrero', 'Jáuregui', 'Táchira'),
  ('Monseñor Miguel Antonio Salas', 'Jáuregui', 'Táchira'),
  ('José María Vargas', 'José María Vargas', 'Táchira'),
  ('Junín', 'Junín', 'Táchira'),
  ('La Petrólea', 'Junín', 'Táchira'),
  ('Quinimarí', 'Junín', 'Táchira'),
  ('Bramón', 'Junín', 'Táchira'),
  ('Libertad', 'Libertad', 'Táchira'),
  ('Cipriano Castro', 'Libertad', 'Táchira'),
  ('Manuel Felipe Rugeles', 'Libertad', 'Táchira'),
  ('Libertador', 'Libertador', 'Táchira'),
  ('Doradas', 'Libertador', 'Táchira'),
  ('Emeterio Ochoa', 'Libertador', 'Táchira'),
  ('San Joaquín de Navay', 'Libertador', 'Táchira'),
  ('Lobatera', 'Lobatera', 'Táchira'),
  ('Constitución', 'Lobatera', 'Táchira'),
  ('Michelena', 'Michelena', 'Táchira'),
  ('Panamericano', 'Panamericano', 'Táchira'),
  ('La Palmita', 'Panamericano', 'Táchira'),
  ('Pedro María Ureña', 'Pedro María Ureña', 'Táchira'),
  ('Nueva Arcadia', 'Pedro María Ureña', 'Táchira'),
  ('Delicias', 'Rafael Urdaneta', 'Táchira'),
  ('Pecaya', 'Rafael Urdaneta', 'Táchira'),
  ('Samuel Darío Maldonado', 'Samuel Darío Maldonado', 'Táchira'),
  ('Boconó', 'Samuel Darío Maldonado', 'Táchira'),
  ('Hernández', 'Samuel Darío Maldonado', 'Táchira'),
  ('La Concordia', 'San Cristóbal', 'Táchira'),
  ('San Juan Bautista', 'San Cristóbal', 'Táchira'),
  ('Pedro María Morantes', 'San Cristóbal', 'Táchira'),
  ('San Sebastián', 'San Cristóbal', 'Táchira'),
  ('Dr. Francisco Romero Lobo', 'San Cristóbal', 'Táchira'),
  ('Seboruco', 'Seboruco', 'Táchira'),
  ('Simón Rodríguez', 'Simón Rodríguez', 'Táchira'),
  ('Sucre', 'Sucre', 'Táchira'),
  ('Eleazar López Contreras', 'Sucre', 'Táchira'),
  ('San Pablo', 'Sucre', 'Táchira'),
  ('Torbes', 'Torbes', 'Táchira'),
  ('Uribante', 'Uribante', 'Táchira'),
  ('Cárdenas', 'Uribante', 'Táchira'),
  ('Juan Pablo Peñalosa', 'Uribante', 'Táchira'),
  ('Potosí', 'Uribante', 'Táchira'),
  ('San Judas Tadeo', 'San Judas Tadeo', 'Táchira'),
  ('Araguaney', 'Andrés Bello', 'Trujillo'),
  ('El Jaguito', 'Andrés Bello', 'Trujillo'),
  ('La Esperanza', 'Andrés Bello', 'Trujillo'),
  ('Santa Isabel', 'Andrés Bello', 'Trujillo'),
  ('Boconó', 'Boconó', 'Trujillo'),
  ('El Carmen', 'Boconó', 'Trujillo'),
  ('Mosquey', 'Boconó', 'Trujillo'),
  ('Ayacucho', 'Boconó', 'Trujillo'),
  ('Burbusay', 'Boconó', 'Trujillo'),
  ('General Ribas', 'Boconó', 'Trujillo'),
  ('Guaramacal', 'Boconó', 'Trujillo'),
  ('Vega de Guaramacal', 'Boconó', 'Trujillo'),
  ('Monseñor Jáuregui', 'Boconó', 'Trujillo'),
  ('Rafael Rangel', 'Boconó', 'Trujillo'),
  ('San Miguel', 'Boconó', 'Trujillo'),
  ('San José', 'Boconó', 'Trujillo'),
  ('Sabana Grande', 'Bolívar', 'Trujillo'),
  ('Cheregüé', 'Bolívar', 'Trujillo'),
  ('Granados', 'Bolívar', 'Trujillo'),
  ('Arnoldo Gabaldón', 'Candelaria', 'Trujillo'),
  ('Bolivia', 'Candelaria', 'Trujillo'),
  ('Carrillo', 'Candelaria', 'Trujillo'),
  ('Cegarra', 'Candelaria', 'Trujillo'),
  ('Chejendé', 'Candelaria', 'Trujillo'),
  ('Manuel Salvador Ulloa', 'Candelaria', 'Trujillo'),
  ('San José', 'Candelaria', 'Trujillo'),
  ('Carache', 'Carache', 'Trujillo'),
  ('La Concepción', 'Carache', 'Trujillo'),
  ('Cuicas', 'Carache', 'Trujillo'),
  ('Panamericana', 'Carache', 'Trujillo'),
  ('Santa Cruz', 'Carache', 'Trujillo'),
  ('Escuque', 'Escuque', 'Trujillo'),
  ('La Unión', 'Escuque', 'Trujillo'),
  ('Santa Rita', 'Escuque', 'Trujillo'),
  ('Sabana Libre', 'Escuque', 'Trujillo'),
  ('El Socorro', 'José Felipe Márquez Cañizalez', 'Trujillo'),
  ('Los Caprichos', 'José Felipe Márquez Cañizalez', 'Trujillo'),
  ('Antonio José de Sucre', 'José Felipe Márquez Cañizalez', 'Trujillo'),
  ('Campo Elías', 'Juan Vicente Campos Elías', 'Trujillo'),
  ('Arnoldo Gabaldón', 'Juan Vicente Campos Elías', 'Trujillo'),
  ('Santa Apolonia', 'La Ceiba', 'Trujillo'),
  ('El Progreso', 'La Ceiba', 'Trujillo'),
  ('La Ceiba', 'La Ceiba', 'Trujillo'),
  ('Tres de Febrero', 'La Ceiba', 'Trujillo'),
  ('El Dividive', 'Miranda', 'Trujillo'),
  ('Agua Santa', 'Miranda', 'Trujillo'),
  ('Agua Caliente', 'Miranda', 'Trujillo'),
  ('El Cenizo', 'Miranda', 'Trujillo'),
  ('Valerita', 'Miranda', 'Trujillo'),
  ('Monte Carmelo', 'Monte Carmelo', 'Trujillo'),
  ('Buena Vista', 'Monte Carmelo', 'Trujillo'),
  ('Santa María del Horcón', 'Monte Carmelo', 'Trujillo'),
  ('Motatán', 'Motatán', 'Trujillo'),
  ('El Baño', 'Motatán', 'Trujillo'),
  ('Jalisco', 'Motatán', 'Trujillo'),
  ('Pampán', 'Pampán', 'Trujillo'),
  ('Flor de Patria', 'Pampán', 'Trujillo'),
  ('La Paz', 'Pampán', 'Trujillo'),
  ('Santa Ana', 'Pampán', 'Trujillo'),
  ('Pampanito', 'Pampanito', 'Trujillo'),
  ('La Concepción', 'Pampanito', 'Trujillo'),
  ('Pampanito II', 'Pampanito', 'Trujillo'),
  ('Betijoque', 'Rafael Rangel', 'Trujillo'),
  ('José Gregorio Hernández', 'Rafael Rangel', 'Trujillo'),
  ('La Pueblita', 'Rafael Rangel', 'Trujillo'),
  ('Los Cedros', 'Rafael Rangel', 'Trujillo'),
  ('Carvajal', 'San Rafael de Carvajal', 'Trujillo'),
  ('Campo Alegre', 'San Rafael de Carvajal', 'Trujillo'),
  ('Antonio Nicolás Briceño', 'San Rafael de Carvajal', 'Trujillo'),
  ('José Leonardo Suárez', 'San Rafael de Carvajal', 'Trujillo'),
  ('Sabana de Mendoza', 'Sucre', 'Trujillo'),
  ('Junín', 'Sucre', 'Trujillo'),
  ('Valmore Rodríguez', 'Sucre', 'Trujillo'),
  ('El Paraíso', 'Sucre', 'Trujillo'),
  ('Andrés Linares', 'Trujillo', 'Trujillo'),
  ('Chiquinquirá', 'Trujillo', 'Trujillo'),
  ('Cristóbal Mendoza', 'Trujillo', 'Trujillo'),
  ('Cruz Carrillo', 'Trujillo', 'Trujillo'),
  ('Matriz', 'Trujillo', 'Trujillo'),
  ('Monseñor Carrillo', 'Trujillo', 'Trujillo'),
  ('Tres Esquinas', 'Trujillo', 'Trujillo'),
  ('Cabimbú', 'Urdaneta', 'Trujillo'),
  ('Jajó', 'Urdaneta', 'Trujillo'),
  ('La Mesa de Esnujaque', 'Urdaneta', 'Trujillo'),
  ('Santiago', 'Urdaneta', 'Trujillo'),
  ('Tuñame', 'Urdaneta', 'Trujillo'),
  ('La Quebrada', 'Urdaneta', 'Trujillo'),
  ('Juan Ignacio Montilla', 'Valera', 'Trujillo'),
  ('La Beatriz', 'Valera', 'Trujillo'),
  ('La Puerta', 'Valera', 'Trujillo'),
  ('Mendoza del Valle de Momboy', 'Valera', 'Trujillo'),
  ('Mercedes Díaz', 'Valera', 'Trujillo'),
  ('San Luis', 'Valera', 'Trujillo'),
  ('Caraballeda', 'Vargas', 'La Guaira'),
  ('Carayaca', 'Vargas', 'La Guaira'),
  ('Carlos Soublette', 'Vargas', 'La Guaira'),
  ('Caruao Chuspa', 'Vargas', 'La Guaira'),
  ('Catia La Mar', 'Vargas', 'La Guaira'),
  ('El Junko', 'Vargas', 'La Guaira'),
  ('La Guaira', 'Vargas', 'La Guaira'),
  ('Macuto', 'Vargas', 'La Guaira'),
  ('Maiquetía', 'Vargas', 'La Guaira'),
  ('Naiguatá', 'Vargas', 'La Guaira'),
  ('Urimare', 'Vargas', 'La Guaira'),
  ('Arístides Bastidas', 'Arístides Bastidas', 'Yaracuy'),
  ('Bolívar', 'Bolívar', 'Yaracuy'),
  ('Chivacoa', 'Bruzual', 'Yaracuy'),
  ('Campo Elías', 'Bruzual', 'Yaracuy'),
  ('Cocorote', 'Cocorote', 'Yaracuy'),
  ('Independencia', 'Independencia', 'Yaracuy'),
  ('José Antonio Páez', 'José Antonio Páez', 'Yaracuy'),
  ('La Trinidad', 'La Trinidad', 'Yaracuy'),
  ('Manuel Monge', 'Manuel Monge', 'Yaracuy'),
  ('Salóm', 'Nirgua', 'Yaracuy'),
  ('Temerla', 'Nirgua', 'Yaracuy'),
  ('Nirgua', 'Nirgua', 'Yaracuy'),
  ('San Andrés', 'Peña', 'Yaracuy'),
  ('Yaritagua', 'Peña', 'Yaracuy'),
  ('San Javier', 'San Felipe', 'Yaracuy'),
  ('Albarico', 'San Felipe', 'Yaracuy'),
  ('San Felipe', 'San Felipe', 'Yaracuy'),
  ('Sucre', 'Sucre', 'Yaracuy'),
  ('Urachiche', 'Urachiche', 'Yaracuy'),
  ('El Guayabo', 'José Joaquín Veroes', 'Yaracuy'),
  ('Farriar', 'José Joaquín Veroes', 'Yaracuy'),
  ('Isla de Toas', 'Almirante Padilla', 'Zulia'),
  ('Monagas', 'Almirante Padilla', 'Zulia'),
  ('San Timoteo', 'Baralt', 'Zulia'),
  ('General Urdaneta', 'Baralt', 'Zulia'),
  ('Libertador', 'Baralt', 'Zulia'),
  ('Marcelino Briceño', 'Baralt', 'Zulia'),
  ('Pueblo Nuevo', 'Baralt', 'Zulia'),
  ('Manuel Guanipa Matos', 'Baralt', 'Zulia'),
  ('Ambrosio', 'Cabimas', 'Zulia'),
  ('Carmen Herrera', 'Cabimas', 'Zulia'),
  ('La Rosa', 'Cabimas', 'Zulia'),
  ('Germán Ríos Linares', 'Cabimas', 'Zulia'),
  ('San Benito', 'Cabimas', 'Zulia'),
  ('Rómulo Betancourt', 'Cabimas', 'Zulia'),
  ('Jorge Hernández', 'Cabimas', 'Zulia'),
  ('Punta Gorda', 'Cabimas', 'Zulia'),
  ('Arístides Calvani', 'Cabimas', 'Zulia'),
  ('Encontrados', 'Catatumbo', 'Zulia'),
  ('Udón Pérez', 'Catatumbo', 'Zulia'),
  ('Moralito', 'Colón', 'Zulia'),
  ('San Carlos del Zulia', 'Colón', 'Zulia'),
  ('Santa Cruz del Zulia', 'Colón', 'Zulia'),
  ('Santa Bárbara', 'Colón', 'Zulia'),
  ('Urribarrí', 'Colón', 'Zulia'),
  ('Carlos Quevedo', 'Francisco Javier Pulgar', 'Zulia'),
  ('Francisco Javier Pulgar', 'Francisco Javier Pulgar', 'Zulia'),
  ('Simón Rodríguez', 'Francisco Javier Pulgar', 'Zulia'),
  ('Guamo-Gavilanes', 'Francisco Javier Pulgar', 'Zulia'),
  ('La Concepción', 'Jesús Enrique Losada', 'Zulia'),
  ('San José', 'Jesús Enrique Losada', 'Zulia'),
  ('Mariano Parra León', 'Jesús Enrique Losada', 'Zulia'),
  ('José Ramón Yépez', 'Jesús Enrique Losada', 'Zulia'),
  ('Jesús María Semprún', 'Jesús María Semprún', 'Zulia'),
  ('Barí', 'Jesús María Semprún', 'Zulia'),
  ('Concepción', 'La Cañada de Urdaneta', 'Zulia'),
  ('Andrés Bello', 'La Cañada de Urdaneta', 'Zulia'),
  ('Chiquinquirá', 'La Cañada de Urdaneta', 'Zulia'),
  ('El Carmelo', 'La Cañada de Urdaneta', 'Zulia'),
  ('Potreritos', 'La Cañada de Urdaneta', 'Zulia'),
  ('Libertad', 'Lagunillas', 'Zulia'),
  ('Alonso de Ojeda', 'Lagunillas', 'Zulia'),
  ('Venezuela', 'Lagunillas', 'Zulia'),
  ('Eleazar López Contreras', 'Lagunillas', 'Zulia'),
  ('Campo Lara', 'Lagunillas', 'Zulia'),
  ('Bartolomé de las Casas', 'Machiques de Perijá', 'Zulia'),
  ('Libertad', 'Machiques de Perijá', 'Zulia'),
  ('Río Negro', 'Machiques de Perijá', 'Zulia'),
  ('San José de Perijá', 'Machiques de Perijá', 'Zulia'),
  ('San Rafael', 'Mara', 'Zulia'),
  ('La Sierrita', 'Mara', 'Zulia'),
  ('Las Parcelas', 'Mara', 'Zulia'),
  ('Luis de Vicente', 'Mara', 'Zulia'),
  ('Monseñor Marcos Sergio Godoy', 'Mara', 'Zulia'),
  ('Ricaurte', 'Mara', 'Zulia'),
  ('Tamare', 'Mara', 'Zulia'),
  ('Antonio Borjas Romero', 'Maracaibo', 'Zulia'),
  ('Bolívar', 'Maracaibo', 'Zulia'),
  ('Cacique Mara', 'Maracaibo', 'Zulia'),
  ('Carracciolo Parra Pérez', 'Maracaibo', 'Zulia'),
  ('Cecilio Acosta', 'Maracaibo', 'Zulia'),
  ('Cristo de Aranza', 'Maracaibo', 'Zulia'),
  ('Coquivacoa', 'Maracaibo', 'Zulia'),
  ('Chiquinquirá', 'Maracaibo', 'Zulia'),
  ('Francisco Eugenio Bustamante', 'Maracaibo', 'Zulia'),
  ('Idelfonzo Vásquez', 'Maracaibo', 'Zulia'),
  ('Juana de Ávila', 'Maracaibo', 'Zulia'),
  ('Luis Hurtado Higuera', 'Maracaibo', 'Zulia'),
  ('Manuel Dagnino', 'Maracaibo', 'Zulia'),
  ('Olegario Villalobos', 'Maracaibo', 'Zulia'),
  ('Raúl Leoni', 'Maracaibo', 'Zulia'),
  ('Santa Lucía', 'Maracaibo', 'Zulia'),
  ('Venancio Pulgar', 'Maracaibo', 'Zulia'),
  ('San Isidro', 'Maracaibo', 'Zulia'),
  ('Altagracia', 'Miranda', 'Zulia'),
  ('Faría', 'Miranda', 'Zulia'),
  ('Ana María Campos', 'Miranda', 'Zulia'),
  ('San Antonio', 'Miranda', 'Zulia'),
  ('San José', 'Miranda', 'Zulia'),
  ('Donaldo García', 'Rosario de Perijá', 'Zulia'),
  ('El Rosario', 'Rosario de Perijá', 'Zulia'),
  ('Sixto Zambrano', 'Rosario de Perijá', 'Zulia'),
  ('San Francisco', 'San Francisco', 'Zulia'),
  ('El Bajo', 'San Francisco', 'Zulia'),
  ('Domitila Flores', 'San Francisco', 'Zulia'),
  ('Francisco Ochoa', 'San Francisco', 'Zulia'),
  ('Los Cortijos', 'San Francisco', 'Zulia'),
  ('Marcial Hernández', 'San Francisco', 'Zulia'),
  ('Santa Rita', 'Santa Rita', 'Zulia'),
  ('El Mene', 'Santa Rita', 'Zulia'),
  ('Pedro Lucas Urribarrí', 'Santa Rita', 'Zulia'),
  ('José Cenobio Urribarrí', 'Santa Rita', 'Zulia'),
  ('Rafael Maria Baralt', 'Simón Bolívar', 'Zulia'),
  ('Manuel Manrique', 'Simón Bolívar', 'Zulia'),
  ('Rafael Urdaneta', 'Simón Bolívar', 'Zulia'),
  ('Bobures', 'Sucre', 'Zulia'),
  ('Gibraltar', 'Sucre', 'Zulia'),
  ('Heras', 'Sucre', 'Zulia'),
  ('Monseñor Arturo Álvarez', 'Sucre', 'Zulia'),
  ('Rómulo Gallegos', 'Sucre', 'Zulia'),
  ('El Batey', 'Sucre', 'Zulia'),
  ('Rafael Urdaneta', 'Valmore Rodríguez', 'Zulia'),
  ('La Victoria', 'Valmore Rodríguez', 'Zulia'),
  ('Raúl Cuenca', 'Valmore Rodríguez', 'Zulia'),
  ('Sinamaica', 'Páez', 'Zulia'),
  ('Alta Guajira', 'Páez', 'Zulia'),
  ('Elías Sánchez Rubio', 'Páez', 'Zulia'),
  ('Guajira', 'Páez', 'Zulia'),
  ('Altagracia', 'Libertador', 'Distrito Capital'),
  ('Antímano', 'Libertador', 'Distrito Capital'),
  ('Caricuao', 'Libertador', 'Distrito Capital'),
  ('Catedral', 'Libertador', 'Distrito Capital'),
  ('Coche', 'Libertador', 'Distrito Capital'),
  ('El Junquito', 'Libertador', 'Distrito Capital'),
  ('El Paraíso', 'Libertador', 'Distrito Capital'),
  ('El Recreo', 'Libertador', 'Distrito Capital'),
  ('El Valle', 'Libertador', 'Distrito Capital'),
  ('La Candelaria', 'Libertador', 'Distrito Capital'),
  ('La Pastora', 'Libertador', 'Distrito Capital'),
  ('La Vega', 'Libertador', 'Distrito Capital'),
  ('Macarao', 'Libertador', 'Distrito Capital'),
  ('San Agustín', 'Libertador', 'Distrito Capital'),
  ('San Bernardino', 'Libertador', 'Distrito Capital'),
  ('San José', 'Libertador', 'Distrito Capital'),
  ('San Juan', 'Libertador', 'Distrito Capital'),
  ('San Pedro', 'Libertador', 'Distrito Capital'),
  ('Santa Rosalía', 'Libertador', 'Distrito Capital'),
  ('Santa Teresa', 'Libertador', 'Distrito Capital'),
  ('Sucre (Catia)', 'Libertador', 'Distrito Capital'),
  ('23 de enero', 'Libertador', 'Distrito Capital')
) AS p(name, municipio_name, estado_name)
JOIN m ON m.name = p.municipio_name AND m.estado_name = p.estado_name;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS parroquias;
DROP TABLE IF EXISTS municipios;
DROP TABLE IF EXISTS estados;
-- +goose StatementEnd